### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by compleatang** [opendata/usodi.org#13]
with Eric's Cloudflare workaround...?

**Comment by waldoj** [comment]
I would quite like the site to be served up via SSL, and since it's GitHub-hosted, that certainly seems like the way to go.

**Comment by waldoj** [comment]
I set up a CloudFlare account, paid 'em $20, added SSL, and edited the whois record to point to CloudFlare. I'm still waiting for the DNS changes to propagate, so there's nothing to see (or test) yet.

**Comment by compleatang** [comment]
Looks like we need to use Full SSL with Strict off according to [this fine comment set](https://github.com/WhiteHouse/playbook/issues/22#issuecomment-51996592). 

Then we'd need to: set the `origin` to `https://opendata.github.io/usodi.org/` with the `https://usoid.org` URL being sent to CloudFlare. That should get us there. 

Once we have that working then I'll add the client side force SSL hack detailed in [Eric's post](https://konklone.com/post/github-pages-now-supports-https-so-use-it) and [this commit](https://github.com/sunlightlabs/congress/commit/6426761a671d46df6fc5d2526bdaf506c39d789c).

**Comment by waldoj** [comment]
See also cc7deac8660a90b97c4cad42b9685daa7aaf401b, which forced all pages _other_ than the home page to SSL.

**Comment by compleatang** [comment]
:thumbsup:
