### ISSUE TITLE
needs more links

### ISSUE THREAD

**Issue by max-mapper** [opendata/usodi.org#4]
blog pages should link to home, and home should have a link to the blog somewhere

**Comment by waldoj** [comment]
Yeah, there's a lot that it needs. :-/ I just wanted something good enough to post tomorrow's announcement. Then I intend to swap the site out to a new template designed for multi-page sites, and move some of the other repositories under this one, as sections of the website.

**Comment by waldoj** [comment]
@konklone made the header clickable in #5—that's a start!

**Comment by compleatang** [comment]
closing for now. mostly it is handled, save for the about page and projects page, but those are covered in #19 and #20.
