### ISSUE TITLE
Does it work for WordPress 3.8.2?

### ISSUE THREAD

**Issue by semenoffalex** [opendata/usodi.org#7]
Hi!

I've tried to use this theme for WordPress 3.8.2, but it says that template and stylesheet are missing.

Is it compatiable with WordPress at all?

Best,
Alex.

**Comment by waldoj** [comment]
This is a the entirety of [usodi.org](http://usodi.org/), as [Jekyll](http://jekyllrb.com/). It's not a template, it's a website. WordPress would have no idea of what to do with it.
